[build]
command = "npm run build"
publish = "dist"
 
[env]
[env.production]
  VITE_SUPABASE_URL = "https://lxbdjoanytvsimcwqjq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4YmRqb2FueXR2c3NpbWN3cWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNjU2ODEsImV4cCI6MjEwMDg0MTY4MX0.aSVYL8fEZToYq8qBPZ1rjbI5HnphstkcE0uVVLasrcw"
 
[[redirects]]
from = "/*"
to = "/index.html"
status = 200